---

webauthn-registration:
  path: /registration
  defaults: {
    _controller: 'SimpleSAML\Module\webauthn\Controller\Registration::main'
  }
  methods: [GET, POST]

webauthn-authprocess:
  path: /authprocess
  defaults: {
    _controller: 'SimpleSAML\Module\webauthn\Controller\AuthProcess::main'
  }
  methods: [GET, POST]

webauthn-webauthn:
  path: /webauthn
  defaults: {
    _controller: 'SimpleSAML\Module\webauthn\Controller\WebAuthn::main'
  }
  methods: [GET, POST]

webauthn-supercharged:
  path: /supercharged
  defaults: {
    _controller: 'SimpleSAML\Module\webauthn\Controller\Supercharged::main'
  }
  methods: [GET, POST]

webauthn-pushbackuserpass:
  path: /pushbackuserpass
  defaults: {
    _controller: 'SimpleSAML\Module\webauthn\Controller\PushbackUserPass::main'
  }
  methods: [GET, POST]

webauthn-regprocess:
  path: /regprocess
  defaults: {
    _controller: 'SimpleSAML\Module\webauthn\Controller\RegProcess::main'
  }
  methods: [GET, POST]

webauthn-managetoken:
  path: /managetoken
  defaults: {
    _controller: 'SimpleSAML\Module\webauthn\Controller\ManageToken::main'
  }
  methods: [GET, POST]
